# Generated by Django 4.2.3 on 2023-07-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='user_creador',
            field=models.IntegerField(null=True),
        ),
    ]
